import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3ee",
        "on-secondary-fixed": "#1b1c1c",
        "inverse-primary": "#ffb4a3",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0eb",
        "on-background": "#1c1c19",
        "on-primary-fixed-variant": "#7c2d1b",
        "on-secondary-container": "#656464",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb4a3",
        "surface-container-highest": "#e5e2dd",
        "secondary-container": "#e4e2e1",
        "on-secondary-fixed-variant": "#474747",
        "outline-variant": "#dac1bb",
        "on-surface-variant": "#54433e",
        "on-surface": "#1c1c19",
        "surface-container-high": "#ebe8e3",
        "surface-tint": "#9b432f",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdad2",
        "tertiary-fixed": "#94f4e3",
        "surface-bright": "#fcf9f4",
        "secondary-fixed-dim": "#c8c6c6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0ede9",
        "on-tertiary-container": "#004139",
        "surface-variant": "#e5e2dd",
        "on-primary-container": "#6a1f0e",
        "inverse-surface": "#31302d",
        "on-error": "#ffffff",
        "tertiary": "#006b5f",
        "tertiary-fixed-dim": "#77d7c7",
        "on-tertiary-fixed-variant": "#005047",
        "secondary-fixed": "#e4e2e1",
        "on-tertiary-fixed": "#00201c",
        "primary": "#9b432f",
        "error": "#ba1a1a",
        "secondary": "#5f5e5e",
        "outline": "#87736d",
        "tertiary-container": "#51b2a3",
        "on-primary-fixed": "#3d0600",
        "surface": "#fcf9f4",
        "background": "#fcf9f4",
        "primary-container": "#f0856c",
        "surface-dim": "#dcdad5"
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-public-sans)", "sans-serif"],
        label: ["var(--font-public-sans)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px", // The CSS says 9999px but the design system says 0px. I'll follow the 0px rule from DESIGN.md unless clarified.
      },
    },
  },
  plugins: [],
};
export default config;
